
 /**
  * This template file was generated by dynaTrace client.
  * The dynaTrace community portal can be found here: http://community.dynatrace.com/
  * For information how to publish a plugin please visit http://community.dynatrace.com/plugins/contribute/
  **/ 

package com.dynatrace.diagnostics.plugins;

import com.dynatrace.diagnostics.pdk.*;

public class OracleTask extends OraclePlugin implements Task {

//	private static final Logger log = Logger.getLogger(OracleTask.class.getName());

	@Override
	public Status setup(TaskEnvironment env) throws Exception {
		return super.setup(env);
	}

	@Override
	public Status execute(TaskEnvironment env) throws Exception {
		return super.execute(env);
	}

	@Override
	public void teardown(TaskEnvironment env) throws Exception {
		super.teardown(env);
	}
}
